[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ─────────────────────────────────────────────────────────
# HEADERS SITE-WIDE (apenas 1 bloco para "/*")
# ─────────────────────────────────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    # CSP (ajuste domínios conforme seus serviços externos)
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      object-src 'none';
      frame-ancestors 'none';
      img-src 'self' data: blob:;
      font-src 'self' data: https://fonts.gstatic.com;
      media-src 'self' data:;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      script-src 'self';
      connect-src 'self' https://api.pipefy.com https://*.netlify.app https://identity.netlify.com;
      worker-src 'self' blob:;
      manifest-src 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """

    # HSTS — remova "preload" se não pretende entrar no hstspreload.org
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Permissions-Policy
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

    # Extras recomendados
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

# ─────────────────────────────────────────────────────────
# NOINDEX em /admin/*
# ─────────────────────────────────────────────────────────
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

# ─────────────────────────────────────────────────────────
# API -> Functions (mantidos)
# ─────────────────────────────────────────────────────────
[[redirects]]
  from = "/api/form"
  to   = "/.netlify/functions/send-to-pipefy"
  status = 200

[[redirects]]
  from = "/api/send-contact"
  to   = "/.netlify/functions/send-contact-to-pipefy"
  status = 200

# ─────────────────────────────────────────────────────────
# HEADERS para /api/* (sem CORS aqui)
# ─────────────────────────────────────────────────────────
[[headers]]
  for = "/api/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

# ─────────────────────────────────────────────────────────
# SPA fallback (por último)
# ─────────────────────────────────────────────────────────
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# www -> apex (opcional se já definiu o Primary Domain)
[[redirects]]
  from = "https://www.stockcapitalmfo.com.br/*"
  to   = "https://stockcapitalmfo.com.br/:splat"
  status = 301
  force = true
 
