[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API -> Function
[[redirects]]
  from = "/api/form"
  to = "/.netlify/functions/send-to-pipefy"
  status = 200

# SPA -> sempre servir index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/send-contact"
  to   = "/.netlify/functions/send-contact-to-pipefy"
  status = 200

