[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API -> Functions
[[redirects]]
  from = "/api/form"
  to   = "/.netlify/functions/send-to-pipefy"
  status = 200

[[redirects]]
  from = "/api/send-contact"
  to   = "/.netlify/functions/send-contact-to-pipefy"
  status = 200

# SPA fallback (deixe por último!)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
