backend:
  name: git-gateway
  branch: main

# permite usar npx decap-server em dev (opcional)
local_backend: true
locale: "pt" 
site_url: "/"
logo_url: "/admin/logo.png"

media_folder: "public/uploads"   # arquivos físicos no repo
public_folder: "/uploads"        # como o site acessa os uploads

# carrega init.js/preview.js
load_config_file: true

# modo de publicação
publish_mode: simple

slug:
  clean_accents: true

editor:
  preview: true

display_url: https://stockcapitalmfo.com.br

collections:
  - name: "cartas"
    label: "Cartas"
    folder: "src/content/cartas"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title",   label: "Título",  widget: "string" }
      - { name: "date",    label: "Data",    widget: "datetime", format: "DD/MM/YYYY", date_format: "DD/MM/YYYY", time_format: false }
      - { name: "summary", label: "Resumo",  widget: "text", required: false }
      - { name: "pdf",     label: "PDF",     widget: "file", media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  - name: "relatorios"
    label: "Relatórios"
    folder: "src/content/relatorios"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title",   label: "Título",  widget: "string" }
      - { name: "date",    label: "Data",    widget: "datetime", format: "DD/MM/YYYY", date_format: "DD/MM/YYYY", time_format: false }
      - { name: "summary", label: "Resumo",  widget: "text", required: false }
      - { name: "pdf",     label: "PDF",     widget: "file", media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  - name: "insights"
    label: "Insights"
    folder: "src/content/insights"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title",   label: "Título",  widget: "string" }
      - { name: "date",    label: "Data",    widget: "datetime", format: "DD/MM/YYYY", date_format: "DD/MM/YYYY", time_format: false }
      - { name: "summary", label: "Resumo",  widget: "text", required: false }
      - { name: "pdf",     label: "PDF",     widget: "file", media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  - name: "compliance"
    label: "Compliance"
    folder: "src/content/compliance"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: "title",   label: "Título",  widget: "string" }
      - { name: "date",    label: "Data",    widget: "datetime", format: "DD/MM/YYYY", date_format: "DD/MM/YYYY", time_format: false }
      - { name: "summary", label: "Resumo",  widget: "text", required: false }
      - { name: "pdf",     label: "PDF",     widget: "file", media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  # === Configurações dos Gráficos (carrossel) ===
  - name: "charts_config"
    label: "Gráficos • Configurações"
    format: "json"
    files:
      - name: "mfo_desempenho"
        label: "Gráfico: Desempenho"
        file: "src/content/rentabilidade/charts/mfo-desempenho.json"
        fields:
          - { name: "type", label: "Tipo (fixo)", widget: "hidden", default: "desempenho" }
          - { name: "title", label: "Título", widget: "string" }
          - { name: "subtitle", label: "Subtítulo", widget: "string", required: false }
          - { name: "notes", label: "Notas (rodapé)", widget: "text", required: false }
          - { name: "autoplay_seconds", label: "Auto-play (segundos)", widget: "number", value_type: "int", min: 0, default: 8 }
          - label: "Acumulação"
            name: "accumulation"
            widget: "select"
            options: ["sum", "compound"]
            default: "sum"
          - label: "Séries (linhas do gráfico)"
            name: "series"
            widget: "list"
            summary: "{{fields.label}} ← {{fields.source}}"
            fields:
              - { name: "label", label: "Rótulo da Série", widget: "string" }
              - label: "Fonte (arquivo JSON)"
                name: "source"
                widget: "file"
                media_library: { allow_multiple: false }
                allow_types: ["json"]
              - { name: "y", label: "Campo Y no JSON (ex.: rendimento)", widget: "string", default: "rendimento" }

      - name: "volatilidade_ltm"
        label: "Gráfico: Volatilidade LTM"
        file: "src/content/rentabilidade/charts/volatilidade-ltm.json"
        fields:
          - { name: "type", label: "Tipo (fixo)", widget: "hidden", default: "volatilidade" }
          - { name: "title", label: "Título", widget: "string", default: "Volatilidade (últimos 12 meses)" }
          - { name: "subtitle", label: "Subtítulo", widget: "string", required: false }
          - { name: "notes", label: "Notas (rodapé)", widget: "text", required: false }
          - { name: "autoplay_seconds", label: "Auto-play (segundos)", widget: "number", value_type: "int", min: 0, default: 8 }
          - label: "Fonte de dados (JSON)"
            name: "source"
            widget: "file"
            media_library: { allow_multiple: false }
            allow_types: ["json"]
          - label: "Opções"
            name: "options"
            widget: "object"
            collapsed: false
            fields:
              - { name: "x", label: "Campo X (data)", widget: "string", default: "date" }
              - { name: "y", label: "Campo Y (volatilidade %)", widget: "string", default: "vol" }
              - { name: "label", label: "Nome da linha", widget: "string", default: "Volatilidade LTM" }
              - { name: "suffix", label: "Sufixo do rótulo final", widget: "string", default: "LTM³", required: false }

      - name: "risco_retorno"
        label: "Gráfico: Risco-Retorno"
        file: "src/content/rentabilidade/charts/risco-retorno.json"
        fields:
          - { name: "type", label: "Tipo (fixo)", widget: "hidden", default: "risco-retorno" }
          - { name: "title", label: "Título", widget: "string", default: "Índices de Risco-Retorno" }
          - { name: "subtitle", label: "Subtítulo", widget: "string", required: false }
          - { name: "notes", label: "Notas (rodapé)", widget: "text", required: false }
          - { name: "autoplay_seconds", label: "Auto-play (segundos)", widget: "number", value_type: "int", min: 0, default: 8 }
          - label: "Fonte (JSON com sortino/sharpe)"
            name: "source"
            widget: "file"
            media_library: { allow_multiple: false }
            allow_types: ["json"]
          - label: "Opções"
            name: "options"
            widget: "object"
            collapsed: false
            fields:
              - { name: "x",  label: "Campo X (data)",   widget: "string", default: "date" }
              - { name: "y1", label: "Campo Y1 (Sortino)", widget: "string", default: "sortino" }
              - { name: "y2", label: "Campo Y2 (Sharpe)",  widget: "string", default: "sharpe" }

  # === Dados dos Gráficos ===
  - name: "charts_data"
    label: "Gráficos • Dados"
    format: "json"
    files:
      - name: "desempenho_portfolio"
        label: "Dados • Desempenho (Portfólio)"
        file: "src/content/rentabilidade/data/desempenho/mfo-portfolio.json"
        fields:
          - label: "Série"
            name: "series"
            widget: "list"
            summary: "{{fields.date}} — {{fields.rendimento}}%"
            fields:
              - { label: "Mês",          name: "date",       widget: "datetime", format: "YYYY-MM", date_format: "YYYY-MM", time_format: false }
              - { label: "Rendimento (%)", name: "rendimento", widget: "number", step: 0.01 }

      - name: "desempenho_alpha"
        label: "Dados • Desempenho (Alpha)"
        file: "src/content/rentabilidade/data/desempenho/alpha.json"
        fields:
          - label: "Série"
            name: "series"
            widget: "list"
            summary: "{{fields.date}} — {{fields.rendimento}}%"
            fields:
              - { label: "Mês",            name: "date",       widget: "datetime", format: "YYYY-MM", date_format: "YYYY-MM", time_format: false }
              - { label: "Rendimento (%)", name: "rendimento", widget: "number", step: 0.01 }

      - name: "desempenho_ifha"
        label: "Dados • Desempenho (IFHA)"
        file: "src/content/rentabilidade/data/desempenho/ifha.json"
        fields:
          - label: "Série"
            name: "series"
            widget: "list"
            summary: "{{fields.date}} — {{fields.rendimento}}%"
            fields:
              - { label: "Mês",            name: "date",       widget: "datetime", format: "YYYY-MM", date_format: "YYYY-MM", time_format: false }
              - { label: "Rendimento (%)", name: "rendimento", widget: "number", step: 0.01 }

      - name: "desempenho_ipca"
        label: "Dados • Desempenho (IPCA)"
        file: "src/content/rentabilidade/data/desempenho/ipca.json"
        fields:
          - label: "Série"
            name: "series"
            widget: "list"
            summary: "{{fields.date}} — {{fields.rendimento}}%"
            fields:
              - { label: "Mês",            name: "date",       widget: "datetime", format: "YYYY-MM", date_format: "YYYY-MM", time_format: false }
              - { label: "Rendimento (%)", name: "rendimento", widget: "number", step: 0.01 }

      - name: "volatilidade_ltm_data"
        label: "Dados • Volatilidade LTM"
        file: "src/content/rentabilidade/data/volatilidade/ltm.json"
        fields:
          - label: "Série"
            name: "series"  
            widget: "list"
            summary: "{{fields.date}} — {{fields.vol}}"
            fields:
              - { label: "Mês",             name: "date", widget: "datetime", format: "YYYY-MM", date_format: "YYYY-MM", time_format: false }
              - { label: "Volatilidade (%)", name: "vol",  widget: "number", step: 0.01 }

      - name: "risco_retorno_sortino_sharpe"
        label: "Dados • Risco-Retorno"
        file: "src/content/rentabilidade/data/risco-retorno/sortino-sharpe.json"
        fields:
          - label: "Série"
            name: "series"
            widget: "list"
            summary: "{{fields.date}} — S:{{fields.sortino}} / Sh:{{fields.sharpe}}"
            fields:
              - { label: "Mês",     name: "date",    widget: "datetime", format: "YYYY-MM", date_format: "YYYY-MM", time_format: false }
              - { label: "Sortino", name: "sortino", widget: "number", step: 0.01 }
              - { label: "Sharpe",  name: "sharpe",  widget: "number", step: 0.01 }
