backend:
  name: git-gateway
  branch: main

# permite usar npx decap-server em dev (opcional)
local_backend: true

site_url: "/"
logo_url: "/admin/logo.png"

media_folder: "public/uploads"   # arquivos físicos no repo
public_folder: "/uploads"        # como o site acessa os uploads

publish_mode: simple             # ou "editorial_workflow" se quiser revisão

slug:
  clean_accents: true

collections:
  - name: "cartas"
    label: "Cartas"
    folder: "src/content/cartas"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: title, label: "Título", widget: string }
      - { name: date,  label: "Data", widget: datetime }
      - { name: summary, label: "Resumo", widget: text }
      - { name: pdf,   label: "PDF", widget: file, media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  - name: "relatorios"
    label: "Relatórios"
    folder: "src/content/relatorios"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: title, label: "Título", widget: string }
      - { name: date,  label: "Data", widget: datetime }
      - { name: summary, label: "Resumo", widget: text }
      - { name: pdf,   label: "PDF", widget: file, media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  - name: "insights"
    label: "Insights"
    folder: "src/content/insights"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: title, label: "Título", widget: string }
      - { name: date,  label: "Data", widget: datetime }
      - { name: summary, label: "Resumo", widget: text }
      - { name: pdf,   label: "PDF", widget: file, media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  - name: "compliance"
    label: "Compliance"
    folder: "src/content/compliance"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { name: title, label: "Título", widget: string }
      - { name: date,  label: "Data", widget: datetime }
      - { name: summary, label: "Resumo", widget: text }
      - { name: pdf,   label: "PDF", widget: file, media_library: { allow_multiple: false }, allow_types: ["pdf"] }

  # >>> Rentabilidade: 5 carteiras fixas (editor altera NOME, MÊS e RENDIMENTO)
  - name: "rentabilidade_carteiras"
    label: "Rentabilidade • Carteiras (dados)"
    format: "json"
    files:
      - name: "carteira1"
        label: "Carteira 1"
        file: "src/content/rentabilidade/carteiras/carteira1.json"
        fields:
          - { label: "Nome (exibição)", name: "nome", widget: "string", hint: "Ex.: CDI, IHFA, IBOV..." }
          - { label: "Slug (fixo)", name: "slug", widget: "hidden", default: "carteira1" }
          - label: "Dados mensais"
            name: "series"
            widget: "series-import"
            hint: "Edite mês a mês ou use 'Escolher arquivo' para importar CSV."

      - name: "carteira2"
        label: "Carteira 2"
        file: "src/content/rentabilidade/carteiras/carteira2.json"
        fields:
          - { label: "Nome (exibição)", name: "nome", widget: "string" }
          - { label: "Slug (fixo)", name: "slug", widget: "hidden", default: "carteira2" }
          - label: "Dados mensais"
            name: "series"
            widget: "series-import"
            hint: "Edite mês a mês ou use 'Escolher arquivo' para importar CSV."            

      - name: "carteira3"
        label: "Carteira 3"
        file: "src/content/rentabilidade/carteiras/carteira3.json"
        fields:
          - { label: "Nome (exibição)", name: "nome", widget: "string" }
          - { label: "Slug (fixo)", name: "slug", widget: "hidden", default: "carteira3" }
          - label: "Dados mensais"
            name: "series"
            widget: "series-import"
            hint: "Edite mês a mês ou use 'Escolher arquivo' para importar CSV."

      - name: "carteira4"
        label: "Carteira 4"
        file: "src/content/rentabilidade/carteiras/carteira4.json"
        fields:
          - { label: "Nome (exibição)", name: "nome", widget: "string" }
          - { label: "Slug (fixo)", name: "slug", widget: "hidden", default: "carteira4" }
          - label: "Dados mensais"
            name: "series"
            widget: "series-import"
            hint: "Edite mês a mês ou use 'Escolher arquivo' para importar CSV."

      - name: "carteira5"
        label: "Carteira 5"
        file: "src/content/rentabilidade/carteiras/carteira5.json"
        fields:
          - { label: "Nome (exibição)", name: "nome", widget: "string" }
          - { label: "Slug (fixo)", name: "slug", widget: "hidden", default: "carteira5" }
          - label: "Dados mensais"
            name: "series"
            widget: "series-import"
            hint: "Edite mês a mês ou use 'Escolher arquivo' para importar CSV."

  # >>> Qual delas aparece no gráfico (ligar/desligar)
  - name: "rentabilidade_dashboard"
    label: "Rentabilidade • Dashboard"
    format: "json"
    files:
      - name: "dashboard"
        label: "Configuração do Gráfico"
        file: "src/content/rentabilidade/dashboard.json"
        fields:
          - label: "Carteiras exibidas"
            name: "exibir"
            widget: "object"
            fields:
              - { label: "Mostrar Carteira 1", name: "carteira1", widget: "boolean", default: true }
              - { label: "Mostrar Carteira 2", name: "carteira2", widget: "boolean", default: true }
              - { label: "Mostrar Carteira 3", name: "carteira3", widget: "boolean", default: true }
              - { label: "Mostrar Carteira 4", name: "carteira4", widget: "boolean", default: false }
              - { label: "Mostrar Carteira 5", name: "carteira5", widget: "boolean", default: false }
