[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  included_files = []

[[redirects]]
  from = "/api/form"
  to = "/.netlify/functions/send-to-pipefy"
  status = 200
